name: Pre-commit Checks

on:
  push:
    branches:
      - main
      - '**' # Runs on all branches
  pull_request:

jobs:
  pre-commit:
    name: Run Pre-commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Run pre-commit
        run: |
          pre-commit install
          pre-commit run --all-files
